name: Build and Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 1.8 and Gradle
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 1.8
          gradle-version: 6.9
      - name: Build with Gradle
        run: ./gradlew build --console=plain
      - name: Run tests
        run: ./gradlew test --console=plain

