name: Build and Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          node-version: '16'
      - name: Build with Gradle
        run: ./gradlew build --console=plain
      - name: Run tests
        run: ./gradlew test --console=plain

