name: Create a comment on new issues

on:
  issues:
    types: [opened]
    
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create Comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          number: ${{ github.event.issue.number }}
          comment: |
            Comment for Issue or GitHub Pull Request
            This is a multi-line test comment
            With GitHub **Markdown** :sparkles:
