name: Create a comment on new issues

on:
  issues:
    types: [opened]
    
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create Comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          comment: |
            Issue title must start with 'ABC-'.
            Auto-closing this issue.
